#!/usr/bin/env -S node --disable-warning=ExperimentalWarning

import { Command } from 'commander';
import pkg from '../package.json' with { type: 'json' };
import registerIndexer from './indexer.js';
import registerNetwork from './network.js';
import registerApps from './apps.js';

const program = new Command();

program
	.name('virgo')
	.description('Virgo CLI')
	.version(pkg.version);

registerIndexer(program);
registerNetwork(program);
registerApps(program);

program.parse();
