#!/usr/bin/env -S node --disable-warning=ExperimentalWarning

import { Command } from 'commander';
import pkg from '../package.json' with { type: 'json' };
import registerNetwork from './network.js';
import registerApps from './apps.js';
import registerIndexer from './indexer.js';

const program = new Command();

program
	.name('virgo')
	.description('virgoOS CLI')
	.version(pkg.version);

registerNetwork(program);
registerApps(program);
registerIndexer(program);

program.parse();
