#!/bin/bash

set -e
set -o pipefail

mkdir -p /var/www/virgo-api/app/cert/
openssl genrsa -out /var/www/virgo-api/app/cert/key.pem
openssl req -new -key /var/www/virgo-api/app/cert/key.pem -out /var/www/virgo-api/app/cert/csr.pem -subj "/CN=virgo"
openssl x509 -req -days 365 -in /var/www/virgo-api/app/cert/csr.pem -signkey /var/www/virgo-api/app/cert/key.pem -out /var/www/virgo-api/app/cert/cert.pem

if test -f /proc/device-tree/model; then
	systemctl enable --now virgo-api.service
fi
