#!/bin/bash

set -o pipefail

if ! ischroot; then
	latest_version=$(/usr/local/bin/n ls-remote 24 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
	installed_versions=$(/usr/local/bin/node -v 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
	if echo "$installed_versions" | grep -qx "$latest_version"; then
		echo "Node $latest_version is already installed. Nothing no update."
	else
		echo "Updating Node..."
		/usr/local/bin/n 24
		/usr/local/bin/n prune
		echo "Node updated."
	fi
fi
