#!/bin/bash

set -o pipefail

if [ $? == 1 ]; then
	latest_lts=$(/usr/local/bin/n --lts 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
	installed_versions=$(/usr/local/bin/node -v 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
	if echo "$installed_versions" | grep -qx "$latest_lts"; then
		echo "Node $latest_lts is already installed. Nothing no update."
	else
		echo "Updating Node..."
		/usr/local/bin/n lts
		/usr/local/bin/n prune
		echo "Node updated."
	fi
fi

#debconf-set-selections <<EOF
#msmtp msmtp/apparmor boolean false
#EOF

#apt install msmtp-mta -y
